project 'FX_margin3.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'FX_margin3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FX_margin3
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'
end
